name: Release application
on:
  push:
    tags:
      - v*
    branches:
      - upgrade-release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Test code
        run: go test -v .

  release:
    name: Release package
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [darwin, linux, windows]
        include:
          - os: darwin
            goos: darwin
            arch: amd64
          - os: linux
            goos: linux
            arch: amd64
          - os: windows
            goos: windows
            arch: amd64
    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        env:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.arch }}
          ref: ${{ github.ref }}
          sha: ${{ github.sha }}
        run: |
          tag=$(echo ${ref} | sed 's#refs/tags/##')
          perl -pi -e "s#%VERSION%#${tag}#g" version/version.go
          perl -pi -e "s#%COMMIT%#${sha}#g" version/version.go
          mkdir dist
          GOOS=${goos} GOARCH=${goarch} go build -v -o dist/docker-base-chaser .
          zip -j -r docker-base-chaser-${{ matrix.os }}.zip dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{github.ref_name}}
          name: Release ${{github.ref_name}}
          generate_release_notes: true
          files: docker-base-chaser-${{ matrix.os }}.zip